# Generated by Django 2.2.24 on 2023-12-07 08:34
import phonenumbers
from django.db import migrations


def fill_pure_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()
    if flats.exists():
        for flat in flats.iterator():
            parse_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
            if phonenumbers.is_valid_number(parse_number):
                flat.owner_pure_phone = f'+{parse_number.country_code}{parse_number.national_number}'
                flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_pure_numbers, move_backward),
    ]
