# Generated by Django 2.2.24 on 2023-12-07 15:03

from django.db import migrations


def fill_flat_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', "Flat")
    owners = Owner.objects.all()
    if owners.exists():
        for owner in owners.iterator():
            owner.flat.set(Flat.objects.filter(owner=owner.name))


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20231207_1736'),
    ]

    operations = [
        migrations.RunPython(fill_flat_owners),
    ]
